compartment_id = "<Your_Compartment_OCID>"
region = "us-phoenix-1"
subnet_id_1 = "<Your_Subnet_1_OCID>"
subnet_id_2 = "<Your_Subnet_2_OCID>"
private_ip_1 = "<Your_Private_IP_1>"
private_ip_2 = "<1Your_Private_IP_1>"
