compartment_id = "<Your_Compartment_OCID>"
region = "us-phoenix-1"
image = "ocid1.image.oc1.phx.aaaaaaaaug4bu37fn6d6ezz7qfvfhqk4bch7gfujrmpyhofwergono3t7waa"
sshkey = "<Your_Public_shh_Key>"
subnet_id_1 = "<Your_Subnet_1_OCID>"
subnet_id_2 = "<Your_Subnet_2_OCID>"
